### ISSUE TITLE
Website redirects following 11ty upgrade

### ISSUE THREAD

**Issue by SimonDarksideJ** [MonoGame/monogame.github.io#78]
### Description

Original links like the following are now failing due to the change in how 11ty manages URLs

> https://docs.monogame.net/articles/packaging_games.html

The URL's are now represented as:

> https://docs.monogame.net/articles/packaging_games/

Is there some configuration or way that 11ty can still accept the old HTML links and redirect to their new home?

**Comment by AristurtleDev** [comment]
Yea, redirects can be handled.  We'll want to ensure they are returned as an HTTP 301: Permanent Redirect response so that search engines update their urls appropriately over time.

Once #80 is finished, that can be used as a basis for finding all existing links that are like this and creating redirects for them.  

Redirects can be put in a [collection](https://github.com/MonoGame/monogame.github.io/tree/main/.config/collections) then a single redirect.njk file can be created that uses the collection and pagination to output the necessary redirect files on build.

(see the frontmatter yaml in the [blog.njk](https://github.com/MonoGame/monogame.github.io/blob/main/content/blog.njk) for example of how the pagination works)

**Comment by AristurtleDev** [comment]
The original docfx links are now generated from #94 

However this original issue uses the `docs.monogame.net` subdomain instead of `www.monogame.net`.  The docs subdomain, as far as I'm aware, no longer exists since the move to GitHub Pages as the site hosting.  However the url path `/articles/packaging_games.html` is now correct.

Unless there are plans to implement the `docs.monogame.net` subdomain, this can be closed now I believe.

**Comment by mrhelmut** [comment]
```docs.monogame.net``` and all sub URLs redirect to the documentation landing page, which I think is safe.

It also seems that google has dereferenced the whole documentation, which means less errors, but also that we now have to wait for the new documentation to be crawled.

I think we're good. I'll leave Simon be the judge.

**Comment by SimonDarksideJ** [comment]
From what I understand, the move back to the API/docs generation to DocFX resolves this issue by basically going back to the way it was :D

WIll double check once the updated site is published.

**Comment by SimonDarksideJ** [comment]
Seems ALL links to https://docs.monogame.net are simply redirecting to https://monogame.net/documentation/

Thoughts @AristurtleDev ?

For the article mentioned in this issue, it's new resting place is
https://monogame.net/articles/packaging_games.html

But any SEO to this page is currently broken

**Comment by SimonDarksideJ** [comment]
Resolved with the separation of docs / website
