### ISSUE TITLE
Enable Tabbed views for documentation

### ISSUE THREAD

**Issue by SimonDarksideJ** [MonoGame/monogame.github.io#79]
### Description

In the migration of documentation from the MS learn site, there is extensive use of tabbed views to be able to show different content based on subject, for example:
![image](https://github.com/MonoGame/monogame.github.io/assets/1793042/26e53d43-8f1a-4f9d-b15c-ec8cb5a2747f)

Is such a view possible under 11ty, and if so how?

**Comment by AristurtleDev** [comment]
A plugin will need to be written for markdown-it to do the tabbed views.  It's possible, just not out-of-the-box functionality.

Example of plugins already created for the site can be found in the https://github.com/MonoGame/monogame.github.io/tree/main/.config/markdownit-plugins directory.

Since markdown has no concept of what a "tab" view is, when creating this, you'll need to either write the css for the tab view or use the [existing bootstrap tabs](https://getbootstrap.com/docs/5.3/components/navs-tabs/#tabs) since we use bootstrap at the foundation of the site.

Once I've wrapped up on #80 I can start on this unless someone wants to jump on it first.

**Comment by Apostolique** [comment]
Is that a feature that's needed? Do our docs use that right now somewhere?

**Comment by SimonDarksideJ** [comment]
> Is that a feature that's needed? Do our docs use that right now somewhere?

Yes, we are in the process of migrating the MS XNA docs and found this useful working with multiple editors.  It will also help cut down the "multiple" setup pages we have.  Ultimately, we can then simplify the "getting started" to a single pages for install and create new project.

**Comment by AristurtleDev** [comment]
Tabbed views are now available when writing articles on the site through the DocFx part as part of #94.
This can be closed now.

**Comment by SimonDarksideJ** [comment]
Agreed, as we moved back to DocFX
